server:
  port: 8082

spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: pablopatino97@gmail.com
    password: gjtfayyqpcexkzih
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost